config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  devise_for :users
  resources :books, only: [:new, :index, :show, :create, :edit, :destroy, :update] do
  resource :favorites, only: [:create, :destroy]
  resources :book_comments, only: [:create,:destroy]
end
  resources :users,only: [:show,:edit,:index,:update]
  get 'home/about' => 'homes#about', as: 'about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

   belongs_to:user
   has_many :favorites, dependent: :destroy
   has_many :book_comments, dependent: :destroy
   has_one_attached :image

  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: { maximum: 200 }

   def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  validates :comment, presence: true

  belongs_to :user
  belongs_to :book

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  validates_uniqueness_of :book_id, scope: :user_id

  belongs_to :user
  belongs_to :book

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :books, dependent: :destroy
         has_many :favorites, dependent: :destroy
         has_many :book_comments, dependent: :destroy
         has_one_attached :profile_image
         validates :name, length: { in: 2..20 }, uniqueness: true
         validates :introduction, length: { maximum: 50 }



  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
     flash[:notice] = "Signed in successfully."
     user_path(current_user)
  end

  def after_sign_up_path_for(resource)
     flash[:notice] = "Welcome! You have signed up successfully."
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
     flash[:notice] = "Signed out successfully."
     root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end

  def destroy
    BookComment.find(params[:id]).destroy
    redirect_to book_path(params[:book_id])
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book=Book.new
  end

  def edit
    @book = Book.find(params[:id])
    unless @book.user_id == current_user.id
      redirect_to books_path
    end
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = current_user
      render:index
    end
  end


  def update
    @book = Book.find(params[:id])
    @user = current_user
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render:edit
    end
    unless @book.user_id == current_user.id
       redirect_to books_path
    end
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
  end


  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title,:body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to user_path(current_user)
    end
  end

  def index
    @book = Book.new
    @current_user = current_user
    @users = User.all
  end

  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    flash[:notice] = "You have updated user successfully."
    redirect_to user_path(@user.id)
    else
      render:edit
    end
     unless @user.id == current_user.id
       redirect_to user_path(current_user)
     end
  end

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_un.html.erb
<div>
  <%= flash[:notice] %>
</div>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= image_tag abc.get_profile_image(100, 100)%>
        <table class="table">
          <tbody>
            <tr>
	            <th>name</th>
	            <th><%= abc.name %></th>
            </tr>
           <tr>
	            <th>introduction</th>
	            <th><%= abc.introduction %></th>
            </tr>
          </tbody>
        </table>


      <div class="row">
        <%= link_to edit_user_path(current_user), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-cog"></i>
        <% end %>
      </div>
      
      <h2 class="mt-3">New book</h2>
      <%= form_with model: book do |f| %>
      <h4>title</h4>
      <%= f.text_field :title %>
      <h4>Opinion</h4>
      <%= f.text_area :body %><br>
      <%= f.submit 'Create Book' %>
      <% end %>
    </div>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %> error prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>Editing Book</h2>
        <%= form_with model: @book do |f| %>
        <div class="form-group">
      <h4>title</h4>
        <%= f.text_field :title, class:"form-control" %>
      <h4>Opinion</h4>
        <%= f.text_area :body, class:"form-control"%><br>
        <%= f.submit 'Update Book', class:"btn btn-secondary" %>
        <% end %>
    </div>
    <div>
      <%= link_to 'Show', book_path(@book.id)%>
      |
      <%= link_to 'Back', books_path%>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %> error prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= render 'un', book: @book, abc: @user %>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
       <thead>
         <tr>
           <th></th>
           <th>Title</th>
           <th>Opinion</th>
           <th colspan="3"></th>
           <th></th>
           <th></th>
          </tr>
        </thead>
        <tbody>
        <% @books.each do |book| %>
          <tr>
            <td><%= link_to image_tag(book.user.get_profile_image(100, 100)), user_path(book.user) %></td>
            <td><%= link_to book.title, book_path(book) %></td>
            <td><%= book.body %></td>
             <td>
              <% if book.favorited_by?(current_user) %>
              <p>
                <%= link_to book_favorites_path(book), method: :delete do %>
                <i class="fas fa-heart" style="color: #f00505;"></i><%= book.favorites.count %>
                <% end %>
              </p>
              <% else %>
              <p>
                <%= link_to book_favorites_path(book), method: :post do %>
                <i class="fas fa-heart" style="color: #2c05f0;"></i><%= book.favorites.count %>
                <% end %>
              </p>
              <% end %>
            </td>
            <td><%="#{book.book_comments.count} コメント" %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<p id="notice"></p>
<div class="row">
  <div class="col-md-3">
    <h2>User info</h2>
    
    <table class="table">
      <tbody>
        <tr>
          <th>name</th>
        </tr>
        <tr>
          <th>introduction</th>
        </tr>
      </tbody>
    </table>
    <div class="row">

    </div>
    <h1 class="mt-3">New Book</h1>
  <%= form_with model: @book do |f| %>
    <h4>Title</h4>
      <%= f.text_field :title %>
    <h4>Opinion</h4>
      <%= f.text_area :opinion %></br>
    <%= f.submit 'Create Book' %>
  <% end %>

app/views/books/show.html.erb
<div>
  <%= flash[:notice] %>
</div>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= image_tag @user.get_profile_image(100, 100)%>
        <table class="table">
          <tbody>
            <tr>
	            <th>name</th>
	            <th><%= @user.name %></th>
            </tr>
           <tr>
	            <th>introduction</th>
	            <th><%= @user.introduction %></th>
            </tr>
          </tbody>
        </table>
      <div class="row">
        <%= link_to edit_user_path(@user.id), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-cog"></i>
        <% end %>
      </div>

      <h2 class="mt-3">New book</h2>
      <%= form_with model: @book_new do |f| %>
      <h4>title</h4>
      <%= f.text_field :title %>
      <h4>Opinion</h4>
      <%= f.text_area :body %><br>
      <%= f.submit 'Create Book' %>
      <% end %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table table-hover table-inverse">
        <tbody>
          <tr>
            <td>
              <%= image_tag @user.get_profile_image(100,100) %><br>
              <%= link_to @book.user.name, user_path(@book.user.id) %>
            </td>
            <td><%= link_to @book.title, book_path(@book) %></td>
            <td><%= @book.body %></td>
            <td>
              <% if @book.user == current_user %>
    　　　　　　　　　<%= link_to "Edit", edit_book_path(@book.id) %>
              <% end %>
            </td>
            <td>
              <% if @book.user == current_user %>
              <%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
              <% end %>
            </td>
            <td>
              <% if @book.favorited_by?(current_user) %>
              <p>
                <%= link_to book_favorites_path(@book), method: :delete do %>
                <i class="fas fa-heart" style="color: #f00505;"></i><%= @book.favorites.count %>
                <% end %>
              </p>
              <% else %>
              <p>
                <%= link_to book_favorites_path(@book), method: :post do %>
                <i class="fas fa-heart" style="color: #2c05f0;"></i><%= @book.favorites.count %>
                <% end %>
              </p>
              <% end %>
            </td>
            <td>
              <p>コメント件数：<%= @book.book_comments.count %></p>
            </td>
          </tr>
        </tbody>
      </table>
      <div>
        <% @book.book_comments.each do |book_comment| %>
        <div>
          <%= image_tag book_comment.user.get_profile_image(100,100) %>
          <%= book_comment.comment %>
          <% if book_comment.user == current_user %>
          <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete %><br>
          <% end %>
          <%= link_to book_comment.user.name, user_path(book_comment.user.id) %>
          <% end %>
        </div>
        <div>
        <%= form_with model: [@book, @book_comment] do |f| %>
        <%= f.text_area :comment, rows: '4', cols: '85'  %><br>
        <%= f.submit "送信" %>
        <% end %>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<main>
    <p id="notice"></p>
    <div class="container">
      <div class="row">
        <div class="px-3 mx-auto">
          <h1>
            welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!
          </h1>
      </div>
    </div>
  </main>

app/views/homes/top.html.erb
    <div>
    <%= flash[:notice] %>
   </div>

    <div class="container">
      <div class="row">
        <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
          <h1>
            welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!
          </h1>
          <p>
            In <storong>Bookers</storong>,
          </p>
          <p>
            you can share and exchange your opinions , inpressions , and emotions</p>
            <p>about various books!</p>
            <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
        </div>
      </div>
        </div>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <div class="navbar-brand">
            <%= link_to "Bookers", root_path, class:'nav-link text-light'  %>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
          aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

             <% if user_signed_in? %>
             <li>
               <%= link_to user_path(current_user), class:'nav-link text-light' do%>
                 <i class="fas fa-home"></i>Home
               <% end %>
             </li>
             <li>
               <%= link_to  users_path, class:'nav-link text-light' do%>
                 <i class="fas fa-users"></i>Users
               <% end %>
             </li>
             <li>
              <%= link_to books_path, class:'nav-link text-light' do%>
                <i class="fas fa-book-open"></i>Books
              <% end %>
             </li>
             <li>
               <%= link_to destroy_user_session_path, method: :delete, class:'nav-link text-light' do %>
                 <i class="fas fa-sign-out-alt"></i>logout
               <% end %>
             </li>
             <% else %>
             <li>
               <%= link_to root_path, class:'nav-link text-light' do %>
                 <i class="fas fa-home"></i>Home
               <% end %>
             </li>
             <li>
               <%= link_to about_path, class:'nav-link text-light' do %>
               <i class="fas fa-link"></i>About
               <% end %>
             </li>
             <li>
               <%= link_to new_user_registration_path, class:'nav-link text-light' do %>
                 <i class="fas fa-user-plus"></i>sign up
               <% end %>
             </li>
             <li>
               <%= link_to new_user_session_path, class:'nav-link text-light' do%>
               <i class="fas fa-sign-in-alt"></i>login
               <% end %>
             </li>
             <% end %>
            </ul>
          </div>
        </div>
      </nav>
  </header>
  <main>
    <%= yield %>
  </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_un.html.erb
<div>
  <%= flash[:notice] %>
</div>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= image_tag abc.get_profile_image(100, 100)%>
        <table class="table">
          <tbody>
            <tr>
	            <th>name</th>
	            <th><%= abc.name %></th>
            </tr>
           <tr>
	            <th>introduction</th>
	            <th><%= abc.introduction %></th>
            </tr>
          </tbody>
        </table>


      <div class="row">
        <%= link_to edit_user_path(current_user), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-cog"></i>
        <% end %>
      </div>


      <h2 class="mt-3">New book</h2>
      <%= form_with model: book do |f| %>
      <h4>title</h4>
      <%= f.text_field :title %>
      <h4>Opinion</h4>
      <%= f.text_area :body %><br>
      <%= f.submit 'Create Book' %>
      <% end %>
    </div>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %> error prohibited this obj from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
   <%= form_with model: @user, url:user_path(@user.id), method: :patch do |f| %>
    <div class="form-group">
    <label for="inputName">Name</label>
    <%= f.text_field :name, class:"form-control" %>
    </div>
    <div class="form-group">
    <label for="inputImage">Image</label>
    <%= f.file_field :profile_image, accept: "image/*" , class: "from-control uesr_profile_image" %>
    </div>
    <div class="form-group">
    <label for="inputName">Introduction</label>
    <%= f.text_field :introduction, class:"form-control" %>
    </div>
    <div class="form-group">
    <%= f.submit 'Update User', class:"btn btn-secondary" %>
    </div>
  <% end %>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'un', book: @book, abc: @current_user %>

<div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table table-hover table-inverse">
       <thead>
         <tr>
           <th>image</th>
           <th>name</th>
           <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= image_tag user.get_profile_image(100,100) %></td>
            <td><%= user.name %></td>
            <td><%= link_to "Show", user_path(user) %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div>
  <%= flash[:notice] %>
</div>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= image_tag @user.get_profile_image(100, 100)%>
        <table class="table">
          <tbody>
            <tr>
	            <th>name</th>
	            <th><%= @user.name %></th>
            </tr>
           <tr>
	            <th>introduction</th>
	            <th><%= @user.introduction %></th>
            </tr>
          </tbody>
        </table>


      <div class="row">
        <%= link_to edit_user_path(@user.id), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-cog"></i>
        <% end %>
      </div>

      <h2 class="mt-3">New book</h2>
      <%= form_with model: @book do |f| %>
      <h4>title</h4>
      <%= f.text_field :title %>
      <h4>Opinion</h4>
      <%= f.text_area :body %><br>
      <%= f.submit 'Create Book' %>
      <% end %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
       <thead>
         <tr>
           <th></th>
           <th>Title</th>
           <th>Opinion</th>
           <th colspan="3"></th>
           <th></th>
           <th></th>
          </tr>
        </thead>
        <tbody>
        <% @books.each do |book| %>
          <tr>
            <td><%= link_to image_tag(book.user.get_profile_image(100, 100)), user_path(book.user) %></td>
            <td><%= link_to book.title, book_path(book) %></td>
            <td><%= book.body %></td>
            <td>
              <% if book.favorited_by?(current_user) %>
              <p>
                <%= link_to book_favorites_path(book), method: :delete do %>
                <i class="fas fa-heart" style="color: #f00505;"></i><%= book.favorites.count %>
                <% end %>
              </p>
              <% else %>
              <p>
                <%= link_to book_favorites_path(book), method: :post do %>
                <i class="fas fa-heart" style="color: #2c05f0;"></i><%= book.favorites.count %>
                <% end %>
              </p>
              <% end %>
            </td>
            <td><%="#{book.book_comments.count} コメント" %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>